### ISSUE TITLE
Improve static page hosted at skipgu.org/past-exams

### ISSUE THREAD

**Issue by michalspano** [skipgu/past-exams#12]
## Improve static page hosted at _skipgu.org/past-exams_

The **static page** hosted at [_skipgu.org/past-exams_](https://skipgu.org/past-exams) needs to be adjusted, namely in the **collapsible** section (there's some conflict among the `html` tags in the `Markdown` file). The changes shall be applied to the `docs` folder and the `README.md` file of it.

### Acceptance Criteria

- [ ] The export at [skipgu.org/past-exams](https://skipgu.org/past-exams) is rendered in the same manner as the root `README.md` file of this repository.
- [ ] The structure of the list (and their items) is preserved in comparison the the `README.md` file from the root of this repository.

**Comment by JonathanPartain** [comment]
I'm on it!

**Comment by michalspano** [comment]
Reopening this **issue**... seems like the **render** works properly on the `local` level, but not on the **remote**.

**Comment by michalspano** [comment]
Continued in #14.
