### ISSUE TITLE
Jekyll - wrong redirects

### ISSUE THREAD

**Issue by 20Attila03** [skipgu/past-exams#23]
On the website `https://github.com/skipgu/past-exams/tree/main` should be added before all **relative** links in order to work properly. (The readme has a static link `https://www.gu.se/` which should not be altered.)

- [X] Prepend `https://github.com/skipgu/past-exams/tree/main` to all relative links (href)
- [X] Make sure that static links are not modified

Script for above:
```html
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const links = document.querySelectorAll("a[href^=\"./exams/\"]");
    links.forEach(link => {
      const code = link.getAttribute("href").slice(8);
      link.href = `https://github.com/skipgu/past-exams/tree/main/exams/${code}`;
    });
  });
</script>
```

**Comment by 20Attila03** [comment]
For some reason sed has no permission. Nor does chmod. It needs inspecting and fixing

**Comment by JonathanPartain** [comment]
```
-- [TDA548 - Grundläggande programvaruutveckling | Introductory software development](./exams/TDA548) 2 exams.
-- [TDA384 - Principles of Concurrent Programming](./exams/TDA384) 2 exams.
+- [TDA548 - Grundläggande programvaruutveckling | Introductory software development]({{ site.github.url }}exams/TDA548) 2 exams
.
+- [TDA384 - Principles of Concurrent Programming]({{ site.github.url }}exams/TDA384) 2 exams.
 
 ***
 
diff --git a/_config.yml b/_config.yml
index 531a2ae..5ab7bac 100644
--- a/_config.yml
+++ b/_config.yml
@@ -4,3 +4,5 @@ commonmark:
   extensions: ["strikethrough", "autolink", "table", "tagfilter"]
 exclude: ["_site", "exams", "descriptionCreator", ".github", "scripts",
          "Gemfile", "Gemfile.lock", "exams.json"] 
+github:
+  url: https://github.com/skipgu/past-exams/tree/main/
```
example diff

**Comment by michalspano** [comment]
> This might be a silly question, but why don't we just hard-code the full url we want to use for each link in the README file?

I agree, @JonathanPartain. I think I actually solved it initially like that, see #28. We can rollback my change and close this issue. What do you think?

**Comment by michalspano** [comment]
Well, no that I think about it, this will work only for the built website, not the `README.md` file within the repository. I suggest that both should work, because some people may simply be reading the `README.md` file from the directory. So I will rollback my changes from #28, because the current implementation does not seem to work. I'll open a PR – can you review it afterwards?

**Comment by JonathanPartain** [comment]
Absolutely, @michalspano , I can review it 😄

**Comment by michalspano** [comment]
> Absolutely, @michalspano , I can review it 😄

Great, @JonathanPartain. I've invited you to this repository, so you should be able to be assigned as a reviewer. Please, see #34 and assign yourself as a reviewer, and see my changes. Any feedback is appreciated.
