### ISSUE TITLE
DIT033 Exam 2022-06-09: Wrong file names

### ISSUE THREAD

**Issue by cynex0** [skipgu/past-exams#24]
The file 'DIT033 Exam 220609.pdf' contains the student answers, and 'DIT033 Student answers 220609.pdf' contains the exam.

**Comment by michalspano** [comment]
Hello, @cynex0. Thanks for opening the issue and good catch! The error has been resolved [2f1526cf5cb1be17cf6f2081b11dcc107717eaac].
